@extends('layouts.app')
@section('content-left')
    @include('layouts.partial.left-table')
@endsection
@section('content-right')
    @include('layouts.partial.map-div')
@endsection
@section('content-bottom')
@include('layouts.partial.bottom-table')
@endsection